config/routes.rb
Groupgift::Application.routes.draw do
  resources :orders

  resources :payments

  resources :votes do
    collection do
      
    end
  end

  resources :gift_selecteds do
    collection do
      get 'remove'
    end
  end

  
  get "finish/index"
  get "finish/payedfailure"
  get "finish/payedsuccessful"
  get "finish/cancelgift"
  

  resources :gift_receivers do
    collection do
      get 'giftSelect'
    end
  end

  resources :gift_groups do
   collection do
    get 'sendmails'
  end
    
  end

  get "gift_group/index"
  

  devise_for :users

  get "welcome/index"
  
  
  

   root :to => "welcome#index"

end

app/models/order.rb
class Order < ActiveRecord::Base
   attr_accessor :card_number, :card_verification
#  validate_on_create :validate_card
  validate(:validate_card,:on=>:create)
  
  def purchase(shared_value)
    value=shared_value.to_f
    value=value*100
    
    response=GATEWAY.purchase(Integer(value),credit_card,:ip=> ip_address, :billing_address=> {:name=>"john M.V",:address1=>"Muttath",:city=>"Thrissur",:state=>"Kerala",:country=>"IN",:ZIP=>"680505"})
    response.success?
    
	
  end
  
  private
  
  def validate_card
    unless credit_card.valid?
      credit_card.errors.full_messages.each do |message  |
        errors.add_to_base message
      end
    end
  end
  
def credit_card
  @credit_card||= ActiveMerchant::Billing::CreditCard.new(
:type=> card_type,
:number=>card_number,
:verification_value=>card_verification,
:month=>card_expires_on.month,
:year=>card_expires_on.year,
:first_name=>first_name,
:last_name=>last_name
)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.xml
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.xml
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.xml
  def new
    @order = Order.new
    @pass=false
    
    session[:coast_per_individual]=params[:coast]
    session[:gift_receiver]=params[:receiverID]
    session[:senderID]=params[:sender]
    @num=Payment.find(:all,:conditions=>{:gift_group_id=>session[:senderID],:gift_receiver_id=>session[:gift_receiver]})
    if @num.count==0 
      
      @pass=true
    
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.xml
  def create
    @order = Order.new(params[:order])
    @order.ip_address=request.remote_ip
    @order.cart_id=1
    @coasttopay=session[:coast_per_individual]

    respond_to do |format|
      if @order.save
        if @order.purchase(@coasttopay)
          @payment = Payment.new
          @payment.gift_group_id=session[:senderID]
          @payment.gift_receiver_id=session[:gift_receiver]
          @payment.payed=@coasttopay
          @payment.save
          format.html { redirect_to(finish_payedsuccessful_path) }
          
        else 
          format.html { redirect_to(finish_payedfailure_path) }
        end
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.xml
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to(@order, :notice => 'Order was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.xml
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to(orders_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%#= f.input :cart_id, :wrapper_html => { :class => 'paymentForm'} %>
    <%#= f.input :ip_address, :wrapper_html => { :class => 'paymentForm'} %>
    <%= f.input :first_name  %>
    <%= f.input :last_name %>
    <%= f.input :card_type,:collection =>[["Visa","visa"],["MasterCard","master"],["Discover","discover"],["American Express","american_express"]] %>
    <%= f.input :card_number,:label=>'Number' %>
    <%= f.input :card_verification,:hint => 'Card verification value (CVV)' %>
    <%= f.input :card_expires_on,:as=>:date,:discard_day=> true, :start_year=> Date.today.year,:end_year=>(Date.today.year+10),:add_month_numbers=>true %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Cart</th>
    <th>Ip address</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Card type</th>
    <th>Card expires on</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.cart_id %></td>
    <td><%= order.ip_address %></td>
    <td><%= order.first_name %></td>
    <td><%= order.last_name %></td>
    <td><%= order.card_type %></td>
    <td><%= order.card_expires_on %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="column span-24 last loginBox" >
<% if @pass==true%>
<%= render 'form' %>
  
  <%  else %>
  Allready payed or Not a valid card
 <%end %>
 </div>

<%#= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cart:</b>
  <%= @order.cart_id %>
</p>

<p>
  <b>Ip address:</b>
  <%= @order.ip_address %>
</p>

<p>
  <b>First name:</b>
  <%= @order.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @order.last_name %>
</p>

<p>
  <b>Card type:</b>
  <%= @order.card_type %>
</p>

<p>
  <b>Card expires on:</b>
  <%= @order.card_expires_on %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>