config/routes.rb
Groupgift::Application.routes.draw do
  resources :orders

  resources :payments

  resources :votes do
    collection do
      
    end
  end

  resources :gift_selecteds do
    collection do
      get 'remove'
    end
  end

  
  get "finish/index"
  get "finish/payedfailure"
  get "finish/payedsuccessful"
  get "finish/cancelgift"
  

  resources :gift_receivers do
    collection do
      get 'giftSelect'
    end
  end

  resources :gift_groups do
   collection do
    get 'sendmails'
  end
    
  end

  get "gift_group/index"
  

  devise_for :users

  get "welcome/index"
  
  
  

   root :to => "welcome#index"

end

app/models/gift_group.rb
class GiftGroup < ActiveRecord::Base
  belongs_to :gift_receiver
  validates(:name, :presence => true)
  validates(:email, :presence => true, 
                    :length => {:minimum => 3, :maximum => 254},
                    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i})
  
  
end

app/controllers/gift_groups_controller.rb
class GiftGroupsController < ApplicationController
  # GET /gift_groups
  # GET /gift_groups.xml
        before_filter :authenticate_user!, :only => [:sendmails,:index]
    
  
  
  def index
    
    @totalCoast=session[:totalamount]
    @individualCoast=0
    #@gift_groups = GiftGroup.all
    @gift_groups = GiftGroup.find(:all,:conditions=>{:gift_receiver_id=>session[:receiverid]})#.page params[:page]
    @receiverId= session[:receiverid]
    @receivename=session[:receivername]
    @gift_group = GiftGroup.new
    @gift_selecteds = GiftSelected.find(:all,:conditions=>{:gift_receiver_id=>session[:receiverid]})
        
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @gift_groups }
    end
  end

  # GET /gift_groups/1
  # GET /gift_groups/1.xml
  def show
    @gift_group = GiftGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @gift_group }
    end
  end

  # GET /gift_groups/new
  # GET /gift_groups/new.xml
  def new
    @gift_group = GiftGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @gift_group }
    end
  end

  # GET /gift_groups/1/edit
  def edit
    @gift_group = GiftGroup.find(params[:id])
  end

  # POST /gift_groups
  # POST /gift_groups.xml
  def create
    @gift_group = GiftGroup.new(params[:gift_group])

    respond_to do |format|
      @gift_group.gift_receiver_id=session[:receiverid]
      if @gift_group.save
        format.html { redirect_to(:controller =>"gift_groups",:action =>"index") }
        
        #format.html { redirect_to(@gift_groups, :notice => 'Added successfully.') }
        format.xml  { render :xml => @gift_group, :status => :created, :location => @gift_group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @gift_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /gift_groups/1
  # PUT /gift_groups/1.xml
  def update
    @gift_group = GiftGroup.find(params[:id])

    respond_to do |format|
      if @gift_group.update_attributes(params[:gift_group])
        format.html { redirect_to(@gift_group, :notice => 'Gift group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @gift_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /gift_groups/1
  # DELETE /gift_groups/1.xml
  def destroy
    @gift_group = GiftGroup.find(params[:id])
    @gift_group.destroy

    respond_to do |format|
      format.html { redirect_to(gift_groups_url) }
      format.xml  { head :ok }
    end
  end
  def sendmails

    @gift_groups = GiftGroup.find(:all,:conditions=>{:gift_receiver_id=>session[:receiverid]})
    @receiverID=session[:receiverid]
    @receiver=session[:receivername]
    @individualCoast=params[:individualCoast]
    @dashboard=DashBoard.new
    @from=current_user.email
    @dashboard.log_in_email=@from
    @dashboard.gift_receiver_id=@receiverID
    @dashboard.save
    @gift_groups.each do |gift_group| 
        UserMailer.inviteletter(gift_group,@receiver,@from,@individualCoast).deliver
    end
    
    respond_to do |format|     
      format.html { redirect_to(:controller =>"finish",:action =>"index") }
    end
    
  end
  
  
end

app/helpers/gift_groups_helper.rb
module GiftGroupsHelper
end

app/views/gift_groups/_form.html.erb
<%= simple_form_for(@gift_group) do |f| %>
  <%= f.error_notification %>

   <div class="inputs">
  
    <%#= f.input :gift_receiver_id,:input_html => { :value => "#{@receiverId}"  } %>
    <%= f.input :name,:input_html => { :class => 'specialname' } %>
    <%= f.input :email,:input_html => { :class => 'specialemail' } %>
    <%#= f.input :shareamount, :input_html => { :class => 'specialamount' },:label => 'Amount'  %>
  </div>

 <!-- <div class="actions">-->
 <div class="addFriendsButton">
    <%= f.button :submit, 'Add'%>
  </div>
<% end %>

app/views/gift_groups/edit.html.erb
<h1>Editing gift_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift_group %> |
<%= link_to 'Back', gift_groups_path %>

app/views/gift_groups/index.html.erb
<div class="column span-24 last" id="headBox">
  <div><h1> Invite Friends </h1></div>
 <div class="column span-6 headboxButton">
 1) The Event 
   
</div>

<div class="column span-6 headboxButton selectedbutton">
  
  2) Invite Friends
</div>
<div class="column span-6 headboxButton last">
  
  3) Confirm it
  
</div>
</div>
<div class="column span-24 last squareBox" >
  
<div id="head1">
  <div id="friends"> 
    Add Friends to share the gift
  </div>
 <%=render :template=>'gift_groups/new'%>
</div> 


<div id="head2">
<div id="friends"> 
  Selected friends for Gift sharing </br>
  <% if @gift_groups.count!=0%>
  Coast per one person <%=@totalCoast/@gift_groups.count %> $
  <%  @individualCoast=@totalCoast/@gift_groups.count %>
  <%end%>
</div>

<table>
  
<% @gift_groups.each do |gift_group| %>
  <tr>
    <!-- <td><%#= gift_group.gift_receiver_id %></td>-->
    <!--<td><%#=gift_group.id  %></td>-->
    <td><%=gift_group.name  %></td>
    <td><%= gift_group.email %></td>
    
    <td><%#= link_to 'Show', gift_group %></td>
    <td><%#= link_to 'Edit', edit_gift_group_path(gift_group) %></td>
    <td><%= link_to 'Delete',gift_group, :confirm => 'Are you sure?', :method => :delete,:class =>"medium button pink" %></td>
     </tr>
<% end %>
</table>

<br />
<%#=  paginate @gift_groups %>
</div>

<%#= link_button_to "Back", url_for(:action=>"index",:controller=>"welcome")%>&nbsp; &nbsp;
<%#= link_button_to "Send Invitation Mails", url_for(sendmails_gift_groups_path)%> &nbsp; &nbsp;
<div id="invitationButton">
<%= link_to "Send Mails",sendmails_gift_groups_path(:individualCoast=>@individualCoast),:class =>"large button pink"%>
</div>
</div>

app/views/gift_groups/new.html.erb
<%= render 'form' %>

<!-- <%#= link_to 'Back', gift_groups_path %> -->

app/views/gift_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Gift receiver:</b>
  <%= @gift_group.gift_receiver_id %>
</p>

<p>
  <b>User:</b>
  <%= @gift_group.email %>
</p>

<p>
  <b>Shareamount:</b>
  <%= @gift_group.shareamount %>
</p>

<%= link_to 'Edit', edit_gift_group_path(@gift_group) %> |
<%= link_to 'Back', gift_groups_path %>