config/routes.rb
Groupgift::Application.routes.draw do
  resources :orders

  resources :payments

  resources :votes do
    collection do
      
    end
  end

  resources :gift_selecteds do
    collection do
      get 'remove'
    end
  end

  
  get "finish/index"
  get "finish/payedfailure"
  get "finish/payedsuccessful"
  get "finish/cancelgift"
  

  resources :gift_receivers do
    collection do
      get 'giftSelect'
    end
  end

  resources :gift_groups do
   collection do
    get 'sendmails'
  end
    
  end

  get "gift_group/index"
  

  devise_for :users

  get "welcome/index"
  
  
  

   root :to => "welcome#index"

end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # GET /payments
  # GET /payments.xml
  def index
    @payments = Payment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.xml
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.xml
  def new
    @payment = Payment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.xml
  def create
    @payment = Payment.new(params[:payment])

    respond_to do |format|
      if @payment.save
        format.html { redirect_to(@payment, :notice => 'Payment was successfully created.') }
        format.xml  { render :xml => @payment, :status => :created, :location => @payment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @payment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /payments/1
  # PUT /payments/1.xml
  def update
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to(@payment, :notice => 'Payment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @payment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.xml
  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to(payments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= simple_form_for(@payment) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :gift_receiver_id %>
    <%= f.input :gift_group_id %>
    <%= f.input :payed %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<div class="column span-24 last squareBoxVote">
  
</div>

app/views/payments/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Gift receiver:</b>
  <%= @payment.gift_receiver_id %>
</p>

<p>
  <b>Gift group:</b>
  <%= @payment.gift_group_id %>
</p>

<p>
  <b>Payed:</b>
  <%= @payment.payed %>
</p>


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>